services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=user
      - DB_PASSWORD=pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FIXER_API_URL=https://data.fixer.io/api
      - FIXER_API_KEY=1335c1cba52925cc0f86366f9b570d6c
      - JWT_SECRET=9ZKgniL0BTcZuWVbfaq4myQ5T0d7ArvA0JNyp1WyYno
      - JWT_EXPIRATION=3600000
    depends_on:
      - db
      - redis


  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"