server:
  port: ${SERVER_PORT}

spring:
  application:
    name: product-category

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    sql:
      init:
        mode: always

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework: INFO

fixer:
  api:
    url: ${FIXER_API_URL}
    key: ${FIXER_API_KEY}